export enum ApiEndPoint {
    serviceTyptList = "/Content/GetServiceTypeList",
    bedRoomList = "/Content/GetBedRoomsList",
    bathRoomList = "/Content/GetBathRoomsList",
    kitchenList = "/Content/GetKitchenList",
    livingAreaList = "/Content/GetLivingAreasList",
    summary = "/Content/GetSummary",
    howOftenDiscount = "/Content/GetHowOftenDiscount",
    extraServiceList = "/Content/GetExtraServiceList",
    timings = "/Content/GetTimings",
    bookService = "/Content/bookService",
    invalid = "/Content/isDiscountCodeValid",
    getSuburb = "/Content/GetSuburb",
    uniqueEmail = "/Content/IsEmailUnique",
    accountCreate = "/Content/CreateAccount",
    login = "/Content/Login",
    verifyPhoneNumber = "/Content/VerifyPhoneNumber",
    intialPayment = "/Content/MannualPayment",
    orderConfirmation = "/Content/OrderConfirmation",
    confirmationSummary = "/Content/getBookingConfirmationSummary",
    authorizeCard = "/Content/AuthorizeCard",
    resetPassword = "/Content/ResetPassword",
    bookingList = "/Content/getBookingList",
    changePassword = "/Content/ChangePassword"
}
