export enum ApiEndPoint {
    serviceTyptList = "/Content/GetServiceTypeList",
    bedRoomList = "/Content/GetBedRoomsList",
    bathRoomList = "/Content/GetBathRoomsList",
    kitchenList = "/Content/GetKitchenList",
    livingAreaList = "/Content/GetLivingAreasList",
    summary = "/Content/GetSummary",
    howOftenDiscount = "/Content/GetHowOftenDiscount",
    extraServiceList = "/Content/GetExtraServiceList",
    timings = "/Content/GetTimings",
    bookService = "/Content/bookService",
    invalid = "/Content/isDiscountCodeValid",
    getSuburb = "/Content/GetSuburb",
    uniqueEmail = "/Content/IsEmailUnique",
    accountCreate = "/Content/CreateAccount",
    login = "/Content/Login",
    verifyPhoneNumber = "/Content/VerifyPhoneNumber",
    intialPayment = "/Content/MannualPayment",
    orderConfirmation = "/Content/OrderConfirmation",
    confirmationSummary = "/Content/getBookingConfirmationSummary",
    authorizeCard = "/Content/AuthorizeCard",
    resetPassword = "/Content/ResetPassword",
    bookingList = "/Content/getBookingList",
    changePassword = "/Content/ChangePassword",
    profileDetails = "/Content/getProfileDetail",
    rescheduleBooking = "/Content/rescheduleBooking",
    cancelBooking = "/Content/cancelBooking",
    register = "/Content/Register",
    verifyEmail = "/Content/emailOTP",
    discountCode = "/Content/sendFirstRegularDiscountCode",
    home = "/Content/GetCleaningStats",


    yearsCleaning = "/Content/GetAdmYearsofExp",
    typeCleaning = "/Content/GetAdmCleaningType",
    admlist = "/Content/GetAdmAreas",
    equipmentList = "/Content/GetAdmEquipments",
    visaType = "/Content/GetAdmVisaType",
    admSocial = "/Content/GetAdmSocial",
    join = "/Content/JoinUs",
    checkList ="/Content/getCheckList",
    exclusion = "/Content/getExclusionsList",
    faq ="/Content/getFaqList",
    privacyPolicy = "/Content/getPrivacyPolicy",
    termsandCondition  = "/Content/getTermsAndCondition",
    googleReviews = "/Content/getReviews"
  
}
